### ISSUE TITLE
[gpodder.model] ERROR: Could not create save_dir

### ISSUE THREAD

**Issue by dreamflasher** [gpodder/gpodder#1190]
Build 41319604 on Windows:

```
1635585349.861915 [gpodder.util] WARNING: Could not create directory C:\Users\df-mi\Documents\gPodder\Downloads\How I Built This with Guy Raz: Vorgang wird nicht unterstützt
1635585349.862913 [gpodder.model] ERROR: Could not create save_dir: C:\Users\df-mi\Documents\gPodder\Downloads\How I Built This with Guy Raz
1635585385.450962 [gpodder.model] WARNING: Unknown external file: C:\Users\df-mi\Documents\gPodder\Downloads\How I Built This with Guy Raz\614d9f37a015be0014a52325.mp3
```

It looks to me like this gio library isn't working properly on Windows. Python3 introduced pathlib which is the pythonic way to interact with filesystems. I don't know if this would solve the problem, but it looks like it to me. Shall I give it a try?

**Comment by elelay** [comment]
Indeed, it seems like gio doesn't work on windows.

We moved from standard file operations to GIO to be able to sync episodes to MTP devices. This is an improvement that I'd like to keep. I'll have a quick look now, but would you have time to investigate this gio unsupported on windows issue?

Thanks,

**Comment by dreamflasher** [comment]
I am trying to have a look – but I can't find a requirements.txt in gpodder, so it's not clear to me which library is actually used.
Is it this one? https://github.com/lazka/giofile
yeah it looks like it's this: https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started
From there it looks to me the requirement is that it's running in msys2 – Likely this won't run in pure python, but requires a certain environment? Then it might become difficult to get this running on Windows?

**Comment by elelay** [comment]
Thanks for looking into it. I've found the issue and will make a PR in a minute

**Comment by elelay** [comment]
The PR is #1191
There will be a windows build to test soon or you can patch your gpodder install with the fix.

We use the python gobject bindings of glib's gio directly, not giofile.

To get started on windows, you can download either the portable or installer version of gPodder and then hack gPodder sources in (YOURINSTALL\lib\python3.9\site-packages\gpodder). Next release will even have a working pip command, to install additional packages.

**Comment by dreamflasher** [comment]
Thanks a lot @elelay , I'll wait for the build that includes this and also removing the sync import. And then hopefully this is running on Windows :)

**Comment by dreamflasher** [comment]
I tested it and it does not solve this issue. 
What I observe: The path exists, I can copy the string and it opens a folder. So path.query_exists() does not return the correct (True) value. 
Instead of make_directories_with_parents you can use this: https://lazka.github.io/pgi-docs/GLib-2.0/functions.html#GLib.mkdir_with_parents – it doesn't fail if the path already exists.

**Comment by elelay** [comment]
I've merged both windows PR so we could test with all changes.
I can't reproduce your issue, with gpodder portable installed to `C:\gpodder-3.10.21-portable` and the fix from #1191.
I've added a `breakpoint()` in `utils.make_directory()` when `path.query_exists()` returns `True` and it is triggered.

What path do you use ?

```
> c:\gpodder-3.10.21-portable\data\lib\python3.9\site-packages\gpodder\util.py(194)make_directory()
-> return True
(Pdb) p path
<__gi__.GLocalFile object at 0x06011d28 (GLocalFile at 0x04292100)>
(Pdb) p path.get_path()
'C:\\gpodder-3.10.21-portable\\config'
```

**Comment by dreamflasher** [comment]
See the first post for the paths that fail. I tried with the latest build that has the merged changes, but I am still getting the errors. 
eg. 
```
1636317292.383764 [gpodder.util] WARNING: Could not create directory C:\Users\df-mi\Documents\gPodder\Downloads\The Skeptics' Guide to the Universe: Vorgang wird nicht unterstützt
1636317318.995225 [gpodder.model] ERROR: Could not create save_dir: C:\Users\df-mi\Documents\gPodder\Downloads\The Skeptics' Guide to the Universe
```

I added a bit of debugging output and for all I get:
```
is_absolute_url: True
path.query_exists: False
```

**Comment by elelay** [comment]
Sorry about that and the delay: I had escaped too much the path in the is_absolute_uri test.
I've just pushed the fix in b8065cadf7fc2. Please can you [try it](https://ci.appveyor.com/project/elelay/gpodder/builds/41692959/artifacts) once it's built?
Thanks,

**Comment by dreamflasher** [comment]
Now I just get `(gpodder-cmd.exe:25216): GLib-GIO-WARNING **: 22:33:52.975: win32 session dbus binary not found: C:\Program Files (x86)\gPodder\bin\\gdbus.exe` – no other errors, the program remains white, and just hangs.

**Comment by elelay** [comment]
Hi,
this warning is harmless. I also have it but gpodder-portable from this build (https://ci.appveyor.com/project/elelay/gpodder/builds/41692959/artifacts) works fine.

Can you try running gPodder in debug mode, to gather more info about the issue ?
Since you already run gpodder-cmd.exe, just add `-v`.

Thanks,

**Comment by greenythebeast** [comment]
Can someone point me in the direction of a Windows build that supports MTP file sync?
