### ISSUE TITLE
Getting error: expected string or bytes-like object

### ISSUE THREAD

**Issue by Snippet24816** [gpodder/gpodder#1311]
![image](https://user-images.githubusercontent.com/108145509/175588254-13bcd78c-1636-4e1b-be21-a631cb72295f.png)
Also the problem is that it reports interminable errors, so I have to click on all the problem items messages one by one, maybe there should be a "yes for all".

**Comment by auouymous** [comment]
What version of gpodder, if not git, could you try installing the latest version (https://ci.appveyor.com/project/elelay/gpodder/builds/43970051/artifacts)? Is it a problem with feeds from multiple hosts, if not, could you provide one of the bad feed urls? Or is it just a bad internet connection that causes all feeds to fail sometimes?

Current gpodder should be displaying error icons on channels and episodes that fail to download, and not showing a dialog.

**Comment by Snippet24816** [comment]
Portableapps packaged portable version 3-10.21 and yes here is the bad feed url https://www.youtube.com/c/solarstone/videos
I think my internet is ok, and other subscriptions load/download properly..

> Current gpodder should be displaying error icons on channels and episodes that fail to download, and not showing a dialog
Oh then is weird.

Also may I ask i know is offtopic but if I open a download folder subscription I get for completed files named with this extension .mp4.partial.f137

**Comment by auouymous** [comment]
> .mp4.partial.f137

This was fixed by #1219, and is available in the above artifacts URL or wait for next release. Those artifacts say 3.10.21 but contain a year of fixes since the 3.10.21 release. You will however need to clean out the existing partial files yourself. Look at the logs in https://gpodder.github.io/docs/user-manual#gpodder-home-folder-and-download-location to get a list of unknown external files that gpodder complains about each time it starts.


> Current gpodder should be displaying error icons on channels and episodes that fail

I just checked and 3.10.21 also displays error icons. That dialog can only appear when something goes wrong setting up the download task, before anything is sent out over the internet. Could you try https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows and post the log around the dialog error message after reproducing it?

It could also be that `#` in the episode title. I think there was issue with it in filenames but can't find it. If that is the problem, upgrading to the artifact might fix the error.

**Comment by Snippet24816** [comment]
> You will however need to clean out the existing partial files yourself

Question how should I do that? Just deleting those files?

> That dialog can only appear when something goes wrong setting up the download task

Maybe is because I set it to immediately download.

> 
Could you try https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows and post the log around the dialog error message after reproducing it?

Sure on it

**Comment by Snippet24816** [comment]
There is something odd starting from gpodder-cmd.exe now I see the error icons but not with the regular PApps launcher.

![image](https://user-images.githubusercontent.com/108145509/175834234-8e4cdf19-09e6-4dd9-87bc-9a0ca153607b.png)

And regarding the error an axemapla is:
3.9\site-packages\gpodder\youtube.py", line 300, in get_real_download_url
    raise YouTubeError('Unsupported DRM content')

**Comment by auouymous** [comment]
> Question how should I do that? Just deleting those files?

Yes.


> Maybe is because I set it to immediately download.

Nope, there is no code before the dialog to download anything.


> should the Portableapps.com version going to be updated soon or should I just better switch to the non paf version?

I don't know what that is but there is a portable version at https://ci.appveyor.com/project/elelay/gpodder/builds/43970051/artifacts.


> raise YouTubeError('Unsupported DRM content')

The builtin youtube client does not support DRM content, you must use youtube-dl to download those episodes.

**Comment by Snippet24816** [comment]
Thank you,

> I don't know what that is but there is a portable version at https://ci.appveyor.com/project/elelay/gpodder/builds/43970051/artifacts.

Okey the paf version is PortableApps.com package extension. 

> The builtin youtube client does not support DRM content, you must use youtube-dl to download those episodes.

So I should use the extension, well when I ran the gpodder-cmd.exe version I forgot about it, but It was in use when the original error happened, but setting it now for gpodder-cmd.exe it returns this

![image](https://user-images.githubusercontent.com/108145509/175861648-3910922f-f393-47b5-9731-40798cb3bbf4.png)

**Comment by auouymous** [comment]
There is no error in that screenshot.

**Comment by Snippet24816** [comment]
But it was stuck in a loop repeating those lines and the app frozen

**Comment by auouymous** [comment]
Can you post the log file? But modify any URLs for feeds that require authentication, or URLs you don't want to share.

**Comment by Snippet24816** [comment]
Sure here it is:
https://drive.google.com/file/d/13RZPrp91qJAgET8HEUJAi3AG1nQnTJqV/view?usp=sharing
Password is: 54tdsfgdfgd

**Comment by auouymous** [comment]
I'm not able to download that file because it says I'm offline and never asks for a password.

What are the errors on videos?

**Comment by Snippet24816** [comment]
Ohh that's weird... the password should be when unpacking the 7z file

```
2022-06-27 20:47:09,491 [gpodder.download] ERROR: Download failed: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
Traceback (most recent call last):
  File "X:\Users\*****\Downloads\Gpodde\gpodder-3.10.21-portable\data\lib\python3.10\site-packages\gpodder\download.py", line 874, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "X:\Users\*****\Downloads\Gpodde\gpodder-3.10.21-portable\data\share\gpodder\extensions\youtube-dl.py", line 95, in retrieve_resume
    res = self._ytdl.fetch_video(self._url, outtmpl, self._my_hook)
  File "X:\Users\*****\Downloads\Gpodde\gpodder-3.10.21-portable\data\share\gpodder\extensions\youtube-dl.py", line 310, in fetch_video
    return ydl.extract_info(url, download=True)
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1418, in extract_info
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1427, in wrapper
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1511, in __extract_info
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1568, in process_ie_result
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2628, in process_video_result
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3085, in process_info
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 969, in report_error
  File "X:/msys64/home/appveyor/_gpodder_build_root/mingw32/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 912, in trouble
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
2022-06-27 20:47:09,978 [gpodder.gtkui.main] INFO: All tasks have finished.
2022-06-27 20:47:10,089 [gpodder.gtkui.main] INFO: All tasks have finished.
2022-06-27 20:47:12,502 [gpodder.download] INFO: No more tasks for Thread-3 (run) to carry out.
2022-06-27 20:47:39,196 [youtube-dl] INFO: Unregistering youtube-dl.
2022-06-27 20:47:39,197 [gpodder.registry] DEBUG: Unregistering feed_handler resolver: <bound method gPodderYoutubeDL.fetch_channel of <youtube-dl.gPodderYoutubeDL object at 0x03bb69a0>>
2022-06-27 20:47:39,198 [gpodder.registry] DEBUG: Unregistering custom_downloader resolver: <bound method gPodderYoutubeDL.custom_downloader of <youtube-dl.gPodderYoutubeDL object at 0x03bb69a0>>
2022-06-27 20:47:39,198 [gpodder.dbsqlite] DEBUG: Commit.
2022-06-27 20:47:39,878 [gpodder.my] INFO: Worker thread may not execute (disabled).
```

**Comment by auouymous** [comment]
```
yt_dlp.utils.DownloadError: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
```

The windows and mac builds of gpodder do not include ffmpeg. I do know that others using the windows build have ffmpeg working with extensions. Go to https://ffmpeg.org/download.html and try installing it or placing the executable in your path if no installer is available. I should probably mention that ffmpeg is needed to use the DASH formats, and maybe add ffmpeg to those builds.

**Comment by Snippet24816** [comment]
> try installing it or placing the executable in your path if no installer is available. 

Thank you so much!!  Placed them in bin path/folder and errors seems to be gone :)

**Comment by Snippet24816** [comment]
Well there's  another issue: episodes are not being automatically donwloaded. Manually downloading works though...

In case is useful from the log:
```
2022-06-30 00:51:31,428 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "X:\gPodder\data\lib\python3.10\site-packages\gpodder\gtkui\main.py", line 2881, in on_gPodder_delete_event
    self.close_gpodder()
  File "X:\gPodder\data\lib\python3.10\site-packages\gpodder\gtkui\main.py", line 2915, in close_gpodder
    self.episode_list_model.background_update = None
AttributeError: 'gPodder' object has no attribute 'episode_list_model'
```

**Comment by auouymous** [comment]
That error looks like something died during startup, the episode list never appeared, and then you closed it. Is that the case? Are there any issues in the log before that error?

@elelay Do automatic updates work in the windows build for you? They are working on linux.

**Comment by Snippet24816** [comment]
> Is that the case?

Yes. And after reopening it it does load the episodes now just no automatic downloading.

This is the log:

```
2022-06-30 00:43:49,103 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Winamp.File\shell\Play\command ([WinError 2] El sistema no puede encontrar el archivo especificado)
2022-06-30 00:43:49,103 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\Applications\foobar2000.exe\shell\open\command ([WinError 2] El sistema no puede encontrar el archivo especificado)
2022-06-30 00:43:49,104 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\QuickTime.mp3\shell\open\command ([WinError 2] El sistema no puede encontrar el archivo especificado)
2022-06-30 00:43:49,104 [gpodder.gtkui.desktopfile] WARNING: Parse HKEY error: HKEY_CLASSES_ROOT\VLC.mp3\shell\open\command ([WinError 2] El sistema no puede encontrar el archivo especificado)
2022-06-30 00:49:04,641 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\gtkui\app.py", line 190, in do_activate
    self.window = gPodder(self, self.bus_name, core.Core(UIConfig, model_class=Model), self.options)
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\gtkui\main.py", line 92, in __init__
    BuilderWidget.__init__(self, None,
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\gtkui\interface\common.py", line 52, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\gtkui\base.py", line 71, in __init__
    self.new()
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\gtkui\main.py", line 187, in new
    self.channels = self.model.get_podcasts()
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\model.py", line 1489, in get_podcasts
    self.children = self.db.load_podcasts(podcast_factory)
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\dbsqlite.py", line 158, in load_podcasts
    cur = self.cursor()
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\dbsqlite.py", line 99, in cursor
    return self.db.cursor()
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\dbsqlite.py", line 90, in db
    schema.upgrade(self._db, self.database_file)
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\schema.py", line 210, in upgrade
    if not list(db.execute('PRAGMA table_info(version)')):
sqlite3.OperationalError: database is locked

2022-06-30 00:49:04,660 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "X:\Gpodder\data\lib\python3.10\site-packages\gpodder\gtkui\main.py", line 1344, in on_treeview_query_tooltip
    if not getattr(treeview, TreeViewHelper.CAN_TOOLTIP) or x > 50 or (column is not None and column != treeview.get_columns()[0]):
AttributeError: 'TreeView' object has no attribute '_gpodder_can_tooltip'
```

**Comment by auouymous** [comment]
> sqlite3.OperationalError: database is locked

Another instance of gpodder might have been running.

**Comment by Snippet24816** [comment]
I triple checked at least right now there isn't another instance, what should I do/how to fix auto downloads?

**Comment by tomasts248** [comment]
I apologize should had done this: gpodder-cmd.exe with -v
and this is what returns:
```
1656799069.162106 [gpodder.download] INFO: *** tasks to do, can start at most 8
 threads, 8 threads currently running
1656799072.709106 [gpodder.util] DEBUG: run_in_background: <bound method Config.
save_thread_proc of <gpodder.gtkui.config.UIConfig object at 0x034d7a18>> (True)
```

**Comment by Snippet24816** [comment]
I apologize should had done this: gpodder-cmd.exe with -v
and this is what returns:
```
1656799069.162106 [gpodder.download] INFO: *** tasks to do, can start at most 8
 threads, 8 threads currently running
1656799072.709106 [gpodder.util] DEBUG: run_in_background: <bound method Config.
save_thread_proc of <gpodder.gtkui.config.UIConfig object at 0x034d7a18>> (True)
```

**Comment by elelay** [comment]
> That error looks like something died during startup, the episode list never appeared, and then you closed it. Is that the case? Are there any issues in the log before that error?
> 
> @elelay Do automatic updates work in the windows build for you? They are working on linux.

The **Search for new episodes on startup** extension works, yes. Is that what you mean?

**Comment by auouymous** [comment]
@elelay I assume @Snippet24816 means the `Update interval` or setting `When new episodes are found` to `Download immediately` in Preferences..Updating to automatically check for and download new episodes while gpodder is running.

**Comment by Snippet24816** [comment]
To clarify I am asked at start to resume downloads, but after that episodes are added to the queue but downloads are never started unless manually set to start download context menu.

**Comment by elelay** [comment]
@Snippet24816 what do you have in *Preferences* > *Updating* ? **When New Episodes are found**

You should select *Download Immediately*.

**Comment by Snippet24816** [comment]
> @Snippet24816 what do you have in _Preferences_ > _Updating_ ? **When New Episodes are found**
> 
> You should select _Download Immediately_.

That's what I have set.

**Comment by auouymous** [comment]
@Snippet24816 So when you close and reopen gpodder while it was downloading episodes, it prompts to resume but the downloads don't begin after resuming? In progress tab, it should say `paused` below each episode, then changed to `queued` when you click the resume button and finally each episode should transition to `downloading` (limited by max downloads in bottom right). Do they transition to queued for you, or remain paused?

**Comment by Snippet24816** [comment]
Well it never downloads on its own.

>  it prompts to resume but the downloads don't begin after resuming?

Exactly.

> o they transition to queued for you, or remain paused?

They transition to queued and stay as queued.

**Comment by elelay** [comment]
Do you have an account on gpodder.net and enabled it?

**Comment by Snippet24816** [comment]
Alright so setting max episodes to 150, and updating the feeds, restarting afterwards and auto-donwloads are working again, so definitively is related to the increase of max episodes, Thing is I increased the limit to get all the past videos but I only need this for the first time. Also question I noticed that when going back to 150 the earlier queued videos are deleted from the list in > Progress,  are past downloaded episodes deleted too?

**Comment by auouymous** [comment]
Downloaded episodes are only deleted if you enable it in clean-up preferences.

**Comment by Snippet24816** [comment]
Okey thanks for that.

**Comment by Snippet24816** [comment]
May I ask if you change the limit in settings.json to 2.000 and regular settings to 2.000 and adding a channel with more than 1500 episodes may the problem be recreated to further debug it?

**Comment by auouymous** [comment]
I have a feed with ~500 episodes but none with 2000. Do you have steps to reproduce this from a fresh install of gpodder? Rename your gpodder folder, start it, make minimal config changes to reproduce the issue. Then delete the test gpodder folder and rename your original. And please provide a feed URL with 2000 episodes if that is required.

**Comment by Snippet24816** [comment]
> And please provide a feed URL with 2000 episodes if that is required.

Sure here is one
https://www.youtube.com/c/WordBox/videos

> 
Do you have steps to reproduce this from a fresh install of gpodder? 

I think it should be:
1. setting 2000 as limit in jdon settings and 2000 limit under regular settings
2. use youtube-dl extension as default.
3. adding the above posted channel.
4. in my case I had to restart gPodder as it got stuck. At least I know it wasn't for not having enough ram ..
5. resume / add to queue on start.

Anyways tomorrow I will try reproducing it on my end and report back.

**Comment by auouymous** [comment]
Gpodder and the youtube-dl extension really needs to show more information in the "Add podcast" dialog and the update progress below channel list. I've seen slow sites take a few minutes to download the RSS feed, and youtube-dl's channel managing takes forever with just 200 episodes, let alone 2000.

It only reached 1gig of ram usage to add that channel but after it added 2000 episodes to the progress list, gtk stopped updating the window and eventually threw `sqlite3.IntegrityError: UNIQUE constraint failed: episode.podcast_id, episode.guid` for every episode. Youtube channels have unique GUIDs so this was most likely a failure somewhere else.

I restarted and resumed the downloads, and all episodes have queued but none have started downloading. The UI is responsive but gpodder is utilizing 100% of one core, and it does stop responding after a while.

```
2022-07-18 02:07:18,163 [gpodder.download] INFO: 1 tasks to do, can start at most 1 threads, 0 threads currently running
2022-07-18 02:07:18,163 [gpodder.download] INFO: Starting new worker thread.
2022-07-18 02:07:18,163 [gpodder.util] DEBUG: run_in_background: <bound method DownloadQueueWorker.run of MainThread> (False)
2022-07-18 02:07:18,163 [gpodder.download] INFO: Starting new thread: Thread-3 (run)
2022-07-18 02:07:19,814 [gpodder.download] INFO: 2 tasks to do, can start at most 1 threads, 1 threads currently running
...
2022-07-18 02:08:48,767 [gpodder.download] INFO: 2000 tasks to do, can start at most 1 threads, 1 threads currently running
```

I'll look more into it tomorrow.

**Comment by elelay** [comment]
Sorry, but I can't reproduce. 
1. problem with gdpr consent => use 
I had it running under gdb w

**Comment by Snippet24816** [comment]
@elelay and perhaps closing it before it has finished before the 30min?
Other than that I'm puzzled as here it happened exactly as @auouymous described it.

**Comment by auouymous** [comment]
I've found the issue, just need to figure out how to fix it.

https://github.com/gpodder/gpodder/blob/master/src/gpodder/gtkui/main.py#L1127 updates the download list every 1.5 seconds. The problem is that 2000 episodes takes longer than 1.5s to update the download list, and timeout_add() is higher priority than idle_add(). Nothing ever changes when updating the download list, because the idle_add() callback is never called, so it never stops the timeout_add() callback and spins forever.

We could increase the 1.5s but that only raises the episode count before it hangs. And slower machines would hang at a much lower number of episodes.

**Comment by auouymous** [comment]
@Snippet24816 https://ci.appveyor.com/project/elelay/gpodder/builds/44366192/artifacts should fix the problem if you want to upgrade.

**Comment by Snippet24816** [comment]
@auouymous 
Thank you so much trying it out tomorrow :)

**Comment by Snippet24816** [comment]
Okey I'm afraid the problem is still there, and now with manual force download start it returns error : Unsupported DRM Content..
I used the portable version in the link, haven't tried the installer one..

**Comment by auouymous** [comment]
> Unsupported DRM Content

Native youtube support does not handle DRM content. Are you using the youtube-dl extension to `manage downloads`?

> Okey I'm afraid the problem is still there

I am able to update the podcast, click download on the new episodes dialog and it downloads all episodes. But the UI is unresponsive and does not refresh, even though the titlebar is rapidly updating the progress of each download and the number of downloads remaining.

After killing and restarting gpodder, I can resume all and everything works fine.

Is this the same problem you have, or something else?

**Comment by auouymous** [comment]
Well, I simply forgot to test the updating part after getting resuming to work. I'll let you know when I find a fix for the rest of it.

**Comment by Snippet24816** [comment]
Oh alright no problem

> I'll let you know when I find a fix for the rest of it.

Okey ;-)

**Comment by auouymous** [comment]
#1367 and #1368 should improve the update and resume process. Mass deleting and pausing from episode list doesn't have a progress dialog yet. I am currently trying to show better progress, and allow cancelling, when adding new podcasts with thousands of episodes.

**Comment by Snippet24816** [comment]
:+1: Let me know if you want me to test it.. ;)

**Comment by auouymous** [comment]
1367 and 1368 have been merged if you want to test them at https://ci.appveyor.com/project/elelay/gpodder/builds/44588608/artifacts

**Comment by Snippet24816** [comment]
Thank you!! I confirm auto downloads are working fine now. There's a minor issue: I cant seem to close this window.. 
![image](https://user-images.githubusercontent.com/108145509/187015963-ff21c5b0-1ba8-4a8e-836a-2fe067680363.png)

**Comment by auouymous** [comment]
Does the log mention anything about youtube-dl or that dialog?

**Comment by Snippet24816** [comment]
About the first yes
```
2022-08-27 03:16:30,300 [gpodder.download] ERROR: Download failed: Unsupported DRM content
Traceback (most recent call last):
  File "E:\*****\data\lib\python3.10\site-packages\gpodder\download.py", line 872, in run
    downloader = DefaultDownloader.custom_downloader(self._config, self.episode)
  File "E:\*****\data\lib\python3.10\site-packages\gpodder\download.py", line 366, in custom_downloader
    res = registry.download_url.resolve(config, None, episode, False)
  File "E:\*****\data\lib\python3.10\site-packages\gpodder\registry.py", line 31, in resolve
    result = resolver(item, *args)
  File "E:\*****\data\lib\python3.10\site-packages\gpodder\youtube.py", line 198, in youtube_real_download_url
    res, duration = get_real_download_url(episode.url, allow_partial, fmt_ids)
  File "E:\*****\data\lib\python3.10\site-packages\gpodder\youtube.py", line 342, in get_real_download_url
    raise YouTubeError('Unsupported DRM content')
gpodder.youtube.YouTubeError: Unsupported DRM content
```

I'm still searching for the dialog..

**Comment by auouymous** [comment]
Does https://ci.appveyor.com/project/elelay/gpodder/builds/44616706/artifacts fix the DRM error? If not, can you run gpodder with `-v` (https://gpodder.github.io/docs/windows.html#debugging-gpodder-on-windows) and look for the "registering youtube-dl" log line and make sure it says "using yt-dlp"?

**Comment by Snippet24816** [comment]
> Does https://ci.appveyor.com/project/elelay/gpodder/builds/44616706/artifacts fix the DRM error?

Yes, working fine now. :+1:

**Comment by auouymous** [comment]
Does https://ci.appveyor.com/project/elelay/gpodder/builds/44804835/artifacts fix the dialog closing problem and everything else in this issue?

**Comment by tomasts248** [comment]
Seems like it does, thank you so much!! I'm still further testing though, if I find something I will update here.

**Comment by Snippet24816** [comment]
Seems like it does, thank you so much!! I'm still further testing though, if I find something I will update here.

**Comment by Snippet24816** [comment]
Ok there is one minor issue : while it is downloading new episodes after an update it cant seem to load the episodes lists of any channel.

**Comment by auouymous** [comment]
Thank you, yet another `idle_add` causing problems. I can reproduce when downloading 16 episodes with my cpu locked to slow. I need to figure out the best way to fix it, but I have found some optimizations that decrease episode list update time by 12%.

**Comment by Snippet24816** [comment]
Anytime! and thanks to you :)

> but I have found some optimizations that decrease episode list update time by 12%.

:+1:

**Comment by auouymous** [comment]
@Snippet24816 #1452 is now merged, does https://ci.appveyor.com/project/elelay/gpodder/builds/45913710/artifacts fix all issues you were having? Does it add any new issues?

**Comment by Snippet24816** [comment]
Hi, sorry for the late answer, I will test and report back! worst case scenario give me some days then I will have more clam to test it throughly

**Comment by Snippet24816** [comment]
I'm testing it  I will report back as soon as I finish

**Comment by Snippet24816** [comment]
Update: everything good except it seems the updating of the episodes is slow
log here in case it helps:

```
sqlite3.IntegrityError: UNIQUE constraint failed: episode.podcast_id, episode.guid
2023-01-30 09:50:03,180 [gpodder.dbsqlite] ERROR: Cannot save <gpodder.gtkui.model.GEpisode object at 0x10bada78>: UNIQUE constraint failed: episode.podcast_id, episode.guid
Traceback (most recent call last):
  File "E:\gPodder_test\data\lib\python3.10\site-packages\gpodder\dbsqlite.py", line 214, in _save_object
    else:
sqlite3.IntegrityError: UNIQUE constraint failed: episode.podcast_id, episode.guid
2023-01-30 09:50:03,180 [gpodder.dbsqlite] ERROR: Cannot save <gpodder.gtkui.model.GEpisode object at 0x10baddc0>: UNIQUE constraint failed: episode.podcast_id, episode.guid
Traceback (most recent call last):
  File "E:\gPodder_test\data\lib\python3.10\site-packages\gpodder\dbsqlite.py", line 214, in _save_object
    else:
sqlite3.IntegrityError: UNIQUE constraint failed: episode.podcast_id, episode.guid
```

**Comment by Snippet24816** [comment]
Okey problem confirmed I made sure I prperly updated the app files, still it cant seem to upadte the feeds, it gets stuck
![image](https://user-images.githubusercontent.com/108145509/215484181-fb94c761-8e63-414f-b1d7-8a55aedf8bf4.png)

**Comment by Snippet24816** [comment]
All good, thnak you so much!!! :-)

**Comment by auouymous** [comment]
Thank you for reporting and testing this.
