### ISSUE TITLE
New episode popup window obscured in the background?

### ISSUE THREAD

**Issue by purrell** [gpodder/gpodder#1451]
I hope this makes sense, but lately I have not been able to use gPodder because when it checks for new episodes the popup window that comes up immediately diseappears and renders the program unusable, but...it never crashes. I can minimize and restore the window, Task Manager says it's healthy, but I can't click around to select anything because (I think) the new episodes popup window is in the background, but I can't find it or move the window around.

When I see it temporarily it's nowhere near the canvas my program is running, but when it disappears I don't know where it goes.

So the only way I can really use the program is to avoid checking for podcast updates that way, and just downloading them manually in the list after force-quitting the previous session.

**Comment by auouymous** [comment]
This issue was fixed by 3a4cd026e90198c6c24fcaf16a285c2168b5c81d. Linux users must upgrade to git, Windows and Mac users can upgrade to a git artifact below, or wait until the next release.

Windows https://ci.appveyor.com/project/elelay/gpodder/builds/45778151/artifacts

Mac https://app.circleci.com/pipelines/github/gpodder/gpodder/544/workflows/fbaec83b-3718-4eb8-8b69-ca4f98b6396c/jobs/912/artifacts

**Comment by purrell** [comment]
THANK YOU

**Comment by amanofgodforever** [comment]
I am having this same issue. I uninstalled gpodder and reinstalled it but the issue remains. I do not know what on earth to do with that artifact link. Any advice would be appreciated

**Comment by auouymous** [comment]
@amanofgodforever Are you running Windows? If so, the artifact is installed the same way you installed the 3.11.0 download.

**Comment by amanofgodforever** [comment]
Yeah, Windows 11 - but I don't see anything to download when I click the artifact link above. This is all I see 
![image](https://user-images.githubusercontent.com/23313197/215616606-5956bb41-a043-493c-944f-36d8d61f6522.png)

**Comment by auouymous** [comment]
Ah, that build is older than a month and the artifacts were deleted. The latest build is at https://ci.appveyor.com/project/elelay/gpodder/builds/46055110/artifacts.

**Comment by amanofgodforever** [comment]
Great, thank you. I've installed that one (despite Avast being unsure of it...) but so far it's not syncing my podcasts and when I try to login to gpodder.net I'm getting a 500 Internal Server error. So I'll try it later and see what happens 😅

**Comment by auouymous** [comment]
Do you mean sync to device or sync to gpodder.net? The gpodder.net web service has had issues for several years, and all versions of the gpodder client will have intermittent failures when accessing it.

**Comment by amanofgodforever** [comment]
Yes, sorry, I meant sync to gpodder.net. I've not had syncing problems before but encountered the 500 internal server error when trying to login on the browser. Should have made that clearer, apologies for the confusion
