### ISSUE TITLE
Youtube: Cannot download video

### ISSUE THREAD

**Issue by auouymous** [gpodder/gpodder#711]
For two days now, more than half of the youtube channels I subscribe to are not downloadable. The problem is that their feeds don't contain 'url_encoded_fmt_stream_map'. The videos can be downloaded with youtube-dl and enabling the youtube-dl extension allows them to be downloaded in gpodder. I don't like using the extension because it takes forever to update, and will be updating with gpodder and then temporarily enabling the extension to download. I am looking for a fix...

**Comment by auouymous** [comment]
https://github.com/ytdl-org/youtube-dl/commit/bf1317d

That is how youtube-dl fixed the issue...

**Comment by fhelwjhewqouywy** [comment]
Good luck with that.
I asked a similar question just hours ago only to have my thread closed without response.  apparently I didn't ask nicely enough because I was annoyed at having to jump through hoops just to ask a question.
This program really needs a proper forum, having to make a github account and hope that your thread doesn't get deleted is kind of a shitty way to get help.

**Comment by auouymous** [comment]
I haven't fully tested this, but it should fix the issue.

http://borg.qzx.com/files/gpodder-711-youtube-player_response.streamingData.formats.patch

Go to the gpodder directory that contains youtube.py and run the following command.

`patch -p3 < {path to this patch}gpodder-711-youtube-player_response.streamingData.formats.patch
`

**Comment by elelay** [comment]
@auouymous so the problem is back? Good that you work on a solution.

Regarding youtube-dl slow updates, you can keep gPodder to manage subscriptions and only use youtube-dl for downloads by unchecking the setting `extensions.youtube-dl.manage_channel`.

**Comment by auouymous** [comment]
@elelay If you are referring to https://github.com/gpodder/gpodder/issues/666, then yes, that issue is back. It is possible it never fully went away, because I get several of these generic errors a week.

Thanks for the setting, any chance of a setting that adds a "download with youtube-dl" option to the episode menu and youtube-dl is only used when that menu option is clicked?

**Comment by elelay** [comment]
> "download with youtube-dl" option to the episode menu

yes, it's possible, but what would be the point? Downloads with youtube-dl are always working, aren't they?

**Comment by auouymous** [comment]
For anyone who wants to use gpodder's youtube code, but manually use youtube-dl when gpodder fails for whatever reason (age-restricted videos). Youtube-dl spams the console and makes errors harder to see, so not good for regular use.

**Comment by elelay** [comment]
ok

**Comment by auouymous** [comment]
The patch is working good so far, but has been updated to check for the adaptiveFormats key before accessing it, in case it doesn't exist in the page.

`http://borg.qzx.com/files/gpodder-711-youtube-player_response.streamingData.formats.patch
`

The following patch updates the second error message to be more readable, especially now that formats no longer only come from the fmt_url_map variable.

`http://borg.qzx.com/files/gpodder-711-change-error-message-to-better-indicate-the-problem.patch`

**Comment by auouymous** [comment]
http://borg.qzx.com/files/gpodder-711-youtube-player_response.streamingData.formats.patch

I fixed some issues with DRM content. The old style stored a DRM url in url key, the new style removes url key and adds a cipher key with an url key inside it.

It looks like all videos use streamingData and the old url_encoded_fmt_stream_map code path will probably never be used. So I merged the second patch because the error doesn't make sense now that only the streamingData path is used. The 'no formats' error is only likely to happen for DRM content, it could mention possible DRM content or it could check for 'cipher' in page when there are no formats and display an unsupported DRM content message (below patch).

http://borg.qzx.com/files/gpodder-711-youtube-unsupported-DRM-content-error-message.patch

**Comment by auouymous** [comment]
Issue #714 becomes a bigger problem with this patch because adaptive formats (audio-only or video-only) have triple digit values. Gpodder can't (yet), but Youtube-dl is able to merge two video and audio formats into a single file. But adding an audio-only format to youtube.preferred_fmt_ids would allow gpodder to download audio-only files from youtube. The audio-only formats could even be added to the settings menu and the list of fallback formats in youtube.py.

Keeping the random format chooser in #714 requires getting rid of adaptive formats.
